"use client";

import {useCallback,useEffect,useState} from "react";
import {Cloud,Download,FileArchive,Lock,LockOpen,Pencil,RefreshCw,Trash2,Upload} from "lucide-react";
import {toast} from "sonner";
import {supabase} from "./supabase";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Switch} from "@/components/ui/switch";

export type CloudSave={id:string;player_id:string;file_sha256:string;file_size:number;player_xp:number;player_level:number|null;current_cash:number;total_fish:number;custom_nickname:string|null;effective_nickname:string;notes:string;is_locked:boolean;source:string;uploaded_at:string;updated_at:string};

async function cloudAction(body:Record<string,unknown>){
  const{data,error}=await supabase.functions.invoke("cloud-saves",{body});
  if(error){let message=error.message;const response=(error as {context?:Response}).context;if(response){try{const payload=await response.clone().json() as {error?:string};if(payload.error)message=payload.error}catch{}}throw new Error(message)}
  if(data?.error)throw new Error(String(data.error));
  return data;
}
const formatNumber=(value:number)=>Number(value||0).toLocaleString();
const formatDate=(value:string)=>new Date(value).toLocaleString([], {dateStyle:"medium",timeStyle:"short"});

export function CloudSavesPage({playerId,adminMode=false,onBack}:{playerId?:string;adminMode?:boolean;onBack?:()=>void}){
  const[saves,setSaves]=useState<CloudSave[]>([]),[playerName,setPlayerName]=useState("your account"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[editing,setEditing]=useState<CloudSave|null>(null),[draft,setDraft]=useState({nickname:"",notes:"",locked:false}),[uploadFile,setUploadFile]=useState<File|null>(null);
  const payload=(extra:Record<string,unknown>={})=>({...extra,...(playerId?{player_id:playerId}:{})});
  const refresh=useCallback(async()=>{setLoading(true);try{const result=await cloudAction(payload({action:"list"}));setSaves(result.saves??[]);setPlayerName(result.player?.username??"player")}catch(error){toast.error(error instanceof Error?error.message:"Could not load cloud saves.")}finally{setLoading(false)}},[playerId]);
  useEffect(()=>{void refresh()},[refresh]);
  function openEdit(save:CloudSave){setEditing(save);setDraft({nickname:save.custom_nickname??"",notes:save.notes??"",locked:save.is_locked})}
  async function saveEdit(){if(!editing)return;setBusy(true);try{await cloudAction(payload({action:"update",save_id:editing.id,custom_nickname:draft.nickname,notes:draft.notes,is_locked:draft.locked}));setEditing(null);await refresh();toast.success("Cloud-save details updated.")}catch(error){toast.error(error instanceof Error?error.message:"Could not update cloud save.")}finally{setBusy(false)}}
  async function remove(save:CloudSave){if(!window.confirm(`Delete ${save.effective_nickname}? This permanently removes that cloud save.`))return;setBusy(true);try{await cloudAction(payload({action:"delete",save_id:save.id}));await refresh();toast.success("Cloud save deleted.")}catch(error){toast.error(error instanceof Error?error.message:"Could not delete cloud save.")}finally{setBusy(false)}}
  async function download(save:CloudSave){setBusy(true);try{const result=await cloudAction(payload({action:"download",save_id:save.id}));const binary=atob(String(result.file_base64));const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const href=URL.createObjectURL(new Blob([bytes],{type:"application/octet-stream"}));const anchor=document.createElement("a");anchor.href=href;anchor.download=String(result.file_name??"game.dat");anchor.click();URL.revokeObjectURL(href)}catch(error){toast.error(error instanceof Error?error.message:"Could not download cloud save.")}finally{setBusy(false)}}
  async function adminUpload(){if(!uploadFile)return;setBusy(true);try{const bytes=new Uint8Array(await uploadFile.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));await cloudAction(payload({action:"upload",source:"admin",file_base64:btoa(binary)}));setUploadFile(null);await refresh();toast.success("Save uploaded to the player’s cloud.")}catch(error){toast.error(error instanceof Error?error.message:"Could not upload cloud save.")}finally{setBusy(false)}}
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{onBack&&<Button variant="ghost" className="mb-2 -ml-3" onClick={onBack}>← Back to Admin Tools</Button>}<p className="eyebrow">Private save archive</p><h1 className="font-display text-3xl font-black sm:text-4xl">{adminMode?`${playerName}’s Cloud Saves`:"Cloud Saves"}</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Up to 15 snapshots are retained. Locked saves stay protected at the bottom of the list; a maximum of five may be locked.</p></div><Button variant="outline" disabled={loading} onClick={()=>void refresh()}><RefreshCw className={loading?"animate-spin":""}/>Refresh</Button></div>
    {adminMode&&<section className="pond-card max-w-3xl p-5"><Upload className="text-cyan-300"/><h2 className="mt-3 section-title">Upload a save for {playerName}</h2><p className="mt-2 text-sm text-slate-400">Use a valid Cornerpond <b>game.dat</b>. It joins the normal 15-save rotation.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Input type="file" accept=".dat,application/octet-stream,text/plain" onChange={event=>setUploadFile(event.target.files?.[0]??null)}/><Button disabled={busy||!uploadFile} onClick={()=>void adminUpload()} className="bg-cyan-300 font-bold text-slate-950"><Upload/>Upload</Button></div></section>}
    {loading?<section className="pond-card grid min-h-40 place-items-center text-slate-400"><RefreshCw className="animate-spin"/></section>:saves.length===0?<section className="pond-card grid min-h-48 place-items-center p-8 text-center"><span><Cloud className="mx-auto size-10 text-cyan-300"/><b className="mt-4 block text-lg">No cloud saves yet</b><small className="mt-1 block text-slate-500">Mission Launch creates the first snapshot after the game starts.</small></span></section>:<div className="space-y-3">{saves.map((save,index)=><article key={save.id} title={save.notes||undefined} className="pond-card flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:p-5"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-cyan-300/10 text-cyan-300">{save.is_locked?<Lock/>:<FileArchive/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-display text-lg font-black">{save.effective_nickname}</h2>{save.is_locked&&<span className="rounded-full bg-amber-300/10 px-2 py-0.5 text-xs font-bold text-amber-200">Locked</span>}<span className="text-xs text-slate-600">#{index+1}</span></div><p className="mt-1 text-sm text-slate-300">{save.player_level!==null?`Level ${save.player_level} · `:""}{formatNumber(save.player_xp)} XP · ${formatNumber(save.current_cash)} cash · {formatNumber(save.total_fish)} fish</p><p className="mt-1 text-xs text-slate-500">Uploaded {formatDate(save.uploaded_at)} · {Math.max(1,Math.ceil(save.file_size/1024))} KB</p>{save.notes&&<p className="mt-2 line-clamp-2 text-sm text-slate-400">{save.notes}</p>}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>openEdit(save)}><Pencil/>Edit</Button>{adminMode&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void download(save)}><Download/>Download</Button>}<Button size="sm" variant="outline" disabled={busy||save.is_locked||saves.length<=5} onClick={()=>void remove(save)} className="border-red-400/30 text-red-200"><Trash2/>Delete</Button></div></article>)}</div>}
    <Dialog open={!!editing} onOpenChange={open=>!open&&setEditing(null)}><DialogContent className="border-slate-700 bg-[#0b1a29] text-slate-100"><DialogHeader><DialogTitle>Edit cloud save</DialogTitle><DialogDescription>A custom nickname stays with this snapshot as it moves down the list. Leave it blank to use the automatic Save number.</DialogDescription></DialogHeader><div className="grid gap-4"><label className="field-label">Nickname<Input maxLength={60} value={draft.nickname} onChange={event=>setDraft({...draft,nickname:event.target.value})} placeholder={editing?.effective_nickname}/></label><label className="field-label">Notes<Textarea maxLength={500} rows={5} value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label><label className="flex items-center justify-between rounded-xl bg-slate-800/55 p-4"><span><b className="flex items-center gap-2">{draft.locked?<Lock/>:<LockOpen/>}Protect this save</b><small className="mt-1 block text-slate-500">Locked saves cannot be rotated out or deleted.</small></span><Switch checked={draft.locked} onCheckedChange={locked=>setDraft({...draft,locked})}/></label></div><DialogFooter><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={busy} onClick={()=>void saveEdit()} className="bg-cyan-300 font-bold text-slate-950">Save details</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
