"use client";

import {useEffect,useMemo,useState} from "react";
import {ChevronDown,ChevronUp,Clock3,Plus,Target,Trophy,Users} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Calendar} from "@/components/ui/calendar";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from "@/components/ui/alert-dialog";
import {toast} from "sonner";
import {LivePlayer} from "./league-data";
import {callTournamentAction,Tournament,tournamentMetrics,TournamentMetric} from "./tournament-data";

const metricLabel=(key:string)=>tournamentMetrics.find(metric=>metric.key===key)?.label??key;
const formatDate=(value:string)=>new Date(value).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"});
const overlapsDay=(date:Date,t:Tournament)=>{const start=new Date(date);start.setHours(0,0,0,0);const end=new Date(date);end.setHours(23,59,59,999);return new Date(t.startsAt)<=end&&new Date(t.endsAt)>=start};
const countdown=(to:string,now:number)=>{const seconds=Math.max(0,Math.floor((new Date(to).valueOf()-now)/1000));const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),secs=seconds%60;return `${days?days+"d ":""}${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(secs).padStart(2,"0")}`};

export function TournamentPage({userId,players,tournaments,onChanged}:{userId:string;players:LivePlayer[];tournaments:Tournament[];onChanged:()=>Promise<void>}){
  const [expanded,setExpanded]=useState<string|null>(null),[retireId,setRetireId]=useState<string|null>(null),[calendarDay,setCalendarDay]=useState<Date|undefined>(new Date()),[now,setNow]=useState(()=>new Date().valueOf()),[busy,setBusy]=useState(false);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date().valueOf()),1000);return()=>window.clearInterval(timer)},[]);
  const playerById=useMemo(()=>new Map(players.map(player=>[player.id,player])),[players]);
  const today=tournaments.filter(t=>overlapsDay(new Date(now),t));
  const next=tournaments.find(t=>new Date(t.startsAt).valueOf()>now);
  const cards=today.length?today:next?[next]:[];
  async function act(action:string,tournamentId:string){setBusy(true);try{await callTournamentAction({action,tournament_id:tournamentId});await onChanged();toast.success(action==="rsvp"?"RSVP saved.":action==="withdraw"?"RSVP withdrawn.":action==="compete"?"You are now competing.":"You retired from the tournament.")}catch(error){toast.error(error instanceof Error?error.message:"Tournament action failed.")}finally{setBusy(false)}}
  return <div className="space-y-6"><div><p className="eyebrow">Scheduled events</p><h1 className="page-title">Fishing tournaments</h1><p className="mt-2 text-slate-400">Opt in, compete live, and follow every scheduled event.</p></div>
    <div className="grid gap-5 xl:grid-cols-2">{cards.length?cards.map(t=>{const start=new Date(t.startsAt).valueOf(),end=new Date(t.endsAt).valueOf(),live=now>=start&&now<end,upcoming=now<start,entry=t.entries.find(e=>e.playerId===userId),open=expanded===t.id,ranked=t.entries.filter(e=>e.state!=="rsvp").sort((a,b)=>b.score-a.score);return <article key={t.id} className="tourney-card !min-h-0 overflow-hidden p-0"><button className="w-full p-4 text-left sm:p-6" onClick={()=>setExpanded(open?null:t.id)}><div className="flex items-start justify-between gap-4"><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${live?"bg-amber-300 text-slate-950":upcoming?"bg-cyan-300/10 text-cyan-200":"bg-slate-700 text-slate-300"}`}>{live?"Live":upcoming?today.length?"Today":"Next tournament":"Finished"}</span>{open?<ChevronUp/>:<ChevronDown/>}</div><Trophy className={`mt-7 size-9 ${live?"text-amber-300":"text-cyan-300"}`}/><h2 className="mt-3 break-words font-display text-2xl font-black">{t.name}</h2><p className="mt-2 break-words text-slate-400">{t.description||`Compete for the highest ${metricLabel(t.metric).toLowerCase()} total.`}</p><div className="mt-5 grid gap-2 text-sm text-slate-300 sm:grid-cols-2"><span><Target className="mr-2 inline size-4 text-cyan-300"/>{metricLabel(t.metric)}</span><span><Users className="mr-2 inline size-4 text-cyan-300"/>{t.entries.length} RSVP{t.entries.length===1?"":"s"}</span><span className="sm:col-span-2"><Clock3 className="mr-2 inline size-4 text-cyan-300"/>{formatDate(t.startsAt)} – {formatDate(t.endsAt)}</span></div>{upcoming&&<p className="mt-5 font-display text-xl font-black text-cyan-200">Begins in {countdown(t.startsAt,now)}</p>}</button>
      <div className="flex flex-wrap gap-2 border-t border-slate-800 px-6 py-4">{upcoming&&!entry&&<Button disabled={busy} onClick={()=>void act("rsvp",t.id)} className="bg-cyan-300 font-bold text-slate-950">RSVP</Button>}{upcoming&&entry?.state==="rsvp"&&<Button disabled={busy} variant="outline" onClick={()=>void act("withdraw",t.id)}>Retract RSVP</Button>}{live&&!entry&&<Button disabled={busy} onClick={()=>void act("compete",t.id)} className="bg-amber-300 font-bold text-slate-950">Compete</Button>}{live&&entry?.state==="rsvp"&&<Button disabled={busy} onClick={()=>void act("compete",t.id)} className="bg-amber-300 font-bold text-slate-950">Compete</Button>}{live&&entry?.state==="competing"&&<Button disabled={busy} variant="destructive" onClick={()=>setRetireId(t.id)}>Retire</Button>}{entry?.state==="retired"&&<span className="self-center text-sm font-bold text-slate-400">Retired — rejoining is disabled</span>}</div>
      {open&&<div className="border-t border-slate-800 p-4 sm:p-6"><p className="eyebrow">Live leaderboard</p><div className="mt-3 space-y-2">{ranked.length?ranked.map((e,index)=>{const player=playerById.get(e.playerId);return <div key={e.playerId} className="grid grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-2 rounded-xl bg-slate-800/55 p-3 sm:grid-cols-[34px_1fr_auto] sm:gap-3"><b className="text-amber-300">#{index+1}</b><span className="min-w-0"><strong className="block truncate">{player?.name??"Player"}{e.state==="retired"?" (Retired)":""}</strong>{player?.activeTitle&&<small className="block truncate text-cyan-300">{player.activeTitle}</small>}</span><b className="font-display text-lg sm:text-xl">{e.score.toLocaleString()}</b></div>}):<p className="rounded-xl border border-dashed border-slate-700 p-4 text-slate-500">No competitors have entered yet.</p>}</div></div>}</article>}):<div className="pond-card p-8 text-slate-400">No tournaments are scheduled yet.</div>}</div>
    <section className="pond-card grid gap-5 overflow-hidden p-4 sm:p-5 lg:grid-cols-[auto_1fr] lg:gap-6"><div className="overflow-x-auto"><Calendar mode="single" selected={calendarDay} onSelect={setCalendarDay} modifiers={{scheduled:tournaments.flatMap(t=>[new Date(t.startsAt),new Date(t.endsAt)])}} modifiersClassNames={{scheduled:"ring-1 ring-cyan-300 text-cyan-200"}}/></div><div className="min-w-0"><p className="eyebrow">Tournament calendar</p><h2 className="section-title">{calendarDay?.toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</h2><div className="mt-4 space-y-3">{tournaments.filter(t=>calendarDay&&overlapsDay(calendarDay,t)).map(t=><button key={t.id} onClick={()=>setExpanded(t.id)} className="block w-full rounded-2xl bg-slate-800/55 p-4 text-left"><b>{t.name}</b><small className="mt-1 block text-slate-400">{metricLabel(t.metric)} · {formatDate(t.startsAt)}</small></button>)}{!tournaments.some(t=>calendarDay&&overlapsDay(calendarDay,t))&&<p className="text-slate-500">No tournament scheduled for this date.</p>}</div></div></section>
    <AlertDialog open={!!retireId} onOpenChange={open=>!open&&setRetireId(null)}><AlertDialogContent className="border-slate-700 bg-[#0b1a29] text-slate-100"><AlertDialogHeader><AlertDialogTitle>Retire from this tournament?</AlertDialogTitle><AlertDialogDescription>This is permanent. Your name and final score remain visible as Retired, and you cannot rejoin.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep competing</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>{if(retireId)void act("retire",retireId);setRetireId(null)}}>Retire permanently</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}

export function TournamentTools({tournaments,onChanged}:{tournaments:Tournament[];onChanged:()=>Promise<void>}){
  const today=new Date().toISOString().slice(0,10);
  const [day,setDay]=useState<Date|undefined>(new Date()),[busy,setBusy]=useState(false),[form,setForm]=useState({name:"",description:"",metric:"fish_caught" as TournamentMetric,startDate:today,endDate:today,startTime:"09:00",endTime:"17:00"});
  async function schedule(){setBusy(true);try{const startsAt=new Date(`${form.startDate}T${form.startTime}`),endsAt=new Date(`${form.endDate}T${form.endTime}`);await callTournamentAction({action:"schedule_tournament",name:form.name,description:form.description,metric:form.metric,starts_at:startsAt.toISOString(),ends_at:endsAt.toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});await onChanged();setForm({...form,name:"",description:""});toast.success("Tournament scheduled.")}catch(error){toast.error(error instanceof Error?error.message:"Could not schedule tournament.")}finally{setBusy(false)}}
  return <div className="space-y-6"><div><p className="eyebrow">Event control</p><h1 className="page-title">Tournament Tools</h1><p className="mt-2 text-slate-400">Schedule single-day or multi-day competitions.</p></div><div className="grid gap-5 xl:grid-cols-[1fr_auto] xl:gap-6"><section className="pond-card p-4 sm:p-5"><h2 className="section-title">Create tournament</h2><div className="mt-5 grid gap-4"><label className="field-label">Tournament name<Input value={form.name} maxLength={80} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field-label">Description<Textarea value={form.description} maxLength={500} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field-label">Metric<Select value={form.metric} onValueChange={value=>setForm({...form,metric:value as TournamentMetric})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{tournamentMetrics.map(metric=><SelectItem key={metric.key} value={metric.key}>{metric.label}</SelectItem>)}</SelectContent></Select></label><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Start date<Input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label className="field-label">Start time<Input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label className="field-label">End date<Input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><label className="field-label">End time<Input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label></div><Button disabled={busy||!form.name.trim()} onClick={()=>void schedule()} className="bg-cyan-300 font-bold text-slate-950"><Plus/>Schedule tournament</Button></div></section><section className="pond-card overflow-x-auto p-2 sm:p-4"><Calendar mode="single" selected={day} onSelect={setDay} modifiers={{scheduled:tournaments.flatMap(t=>[new Date(t.startsAt),new Date(t.endsAt)])}} modifiersClassNames={{scheduled:"ring-1 ring-cyan-300 text-cyan-200"}}/><div className="mt-3 max-w-[310px] space-y-2">{tournaments.filter(t=>day&&overlapsDay(day,t)).map(t=><div key={t.id} className="rounded-xl bg-slate-800/55 p-3"><b>{t.name}</b><small className="block text-slate-400">{formatDate(t.startsAt)}</small></div>)}</div></section></div></div>
}
